title = "🖋️ Emanuele Addis"
description = "My personal website!"
base_url = "https://emanueleaddis.it"
default_language = "en"

theme = "apollo"
taxonomies = [{ name = "topics" }]

compile_sass = false
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

build_search_index = true
minify_html = true

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown.highlighting]
dark_theme = "ayu-dark"
light_theme = "everforest-light"
style = "class"
error_on_missing_language = true

[extra]
fediverse = false
fediverse_creator = ""
socials = [
    { name = "github", url = "https://github.com/acwazz", icon = "github" },
    { name = "soundcloud", url = "https://soundcloud.com/emanuele-addis", icon = "soundcloud" },
    { name = "spotify", url = "https://open.spotify.com/intl-it/artist/32KsSdutnnbkiefiTeAeTT?si=At8nJehVSIah63-VW1-2lQ", icon = "spotify" },
    { name = "rss", url = "/atom.xml", icon = "rss" },
]
menu = [
    { name = "<home>", url = "/", weight = 1 },
#    { name = "<blog>", url = "/blog", weight = 2 },
#    { name = "<topics>", url = "/topics", weight = 3 },
]
theme = "toggle"
favicon = "imgs/favicon.png"
toc = true
fancy_code = true
use_cdn = false
stylesheets = ["css/overrides.css", "css/components.css"]

[extra.taxonomies]
sort_by = "name"
reverse = false
